version: '3'

services: 
  mysql:
    image: maxdev888/todo-list-app:database
    ports:
      - 3000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=maxdev789
    restart: always
    volumes:
      - mysqldb:/var/lib/mysql
  
  frontend:
    image: maxdev888/todo-list-app:frontend
    ports:
      - 4173:4173
    restart: always

  backend:
    image: maxdev888/todo-list-app:backend
    ports:
      - 8081:8081
    restart: always
    depends_on: 
      - mysql
    
volumes:
  mysqldb: