apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: todolist-app
spec:
  selector:
    matchLabels:
      app: todolist-app
      tier: frontend
#  strategy:
#    type: Recreate
  template:
    metadata:
      name: react-pod
      labels:
        app: todolist-app
        tier: frontend
    spec:
      containers:
      - image: maxdev888/todo-list-app:frontend-19
        name: frontend-container
        ports:
        - containerPort: 4173
          name: react-app-port
---
apiVersion: v1
kind: Service
metadata:
  name: frontend 
  labels:
    app: todolist-app
    tier: frontend
spec:
  ports:
    - protocol: TCP 
      port: 4173
      targetPort: 4173
  selector:
    app: todolist-app
    tier: frontend